2023.1 cherries
stackhpc/networking-generic-switch pull request #67
Opened 2023-09-04 12:18 UTC by mnasiadka

2023-09-04 12:31 UTC, markgoddard requested changes

2023-09-04 12:31 UTC, markgoddard commented on networking_generic_switch/devices/__init__.py
> +    {'name': 'vlan_translation_supported', 'default': False}
Duplicate option

2023-09-06 07:13 UTC, mnasiadka commented on networking_generic_switch/batching.py
> +            etcd_client = etcd3gw.Etcd3Client(
Done

2023-09-06 07:18 UTC, mnasiadka commented on networking_generic_switch/devices/__init__.py
> +    {'name': 'vlan_translation_supported', 'default': False}
Done

2023-09-07 12:15 UTC, merged